### ISSUE TITLE
Registry with credentials on aspirate init

### ISSUE THREAD

**Issue by adamtrip** [prom3theu5/aspirational-manifests#101]
On running `aspirate init` it would be cool to support private registries with credentials. I know it already supports custom registries but would be nice to support credentials as well.

**Comment by prom3theu5** [comment]
Hi Adam

I don't really want to add registry credentials to the init command, as there is no secret management in init
Its just lightweight fall back values.

Because the docker or podman daemons are used, whatever your system is signed in to aspirate has access to.

Now when it comes to deployment, thats slightly different as you'd also require an imagePullSecret in each deployment, and creation of the imagePullSecret within the cluster.
I'd be willing to add them to the generate command as optional flags - that can then use the secret provider system to encode the values, which apply can decrypt

**Comment by prom3theu5** [comment]
Will track in #106
