### ISSUE TITLE
Helm Chart Generation Not Working in 0.7.0

### ISSUE THREAD

**Issue by josephaw1022** [prom3theu5/aspirational-manifests#182]
### 🔥 Bug Description
When I generate the yaml file using aspirate generate, I no longer see any prompt for generating the helm charts as I did in version .6. 

### 🔍 Steps to Reproduce the Bug
1. Create aspire project
2. run aspirate init
3. run aspirate build
4. run aspirate generate

### 🧯 Possible Solution
🤷‍♂️ Not too familiar with the codebase so I am not sure how everything works and all.

**Comment by prom3theu5** [comment]
Hi. Helm has now moved to a full separate output format rather than relying on kustomize like it did previously. Now it directly creates the manifests and doesn't require kustomize to be on the machine. Previously it wrote kustomize manifests then rendered them to stdout and then parsed that but it was mega inefficient. 

If you run 'aspirate generate --output-format helm' you will get the chart. 

You only need to do this once as it writes your selected output format to aspirate-state.json so that all future runs reuse whatever you set the last values to 😄

**Comment by josephaw1022** [comment]
good stuff! Thank you!
