### ISSUE TITLE
Secrets management always disabled when `generate` output is compose

### ISSUE THREAD

**Issue by Paxol** [prom3theu5/aspirational-manifests#197]
What is the reason behind this? I wanted to use the non interactive mode to generate the docker-compose.yaml file, but I can't because there are some needed secrets. Is there another way to provide the secrets?
Thanks you in advance.

**Comment by prom3theu5** [comment]
Hi

Purely because right now docker-compose when targeting docker / podman and not swarm would store these values as plain text anyway
They wouldn't be secret, they'd purely be a separate file which contained all the values as env vars.

#151 is a feature request that outputs them to an env vars file, and replaces the values in the compose with the env counterpart - but thats not started yet

**Comment by prom3theu5** [comment]
I've reimplemented secret management tonight so that its compatible with compose now.
It will no longer disable secrets - and input state will also be captured :)
