### ISSUE TITLE
AspireWithJavaScript Docker compose not shown frontend

### ISSUE THREAD

**Issue by timeshift92** [prom3theu5/aspirational-manifests#205]
### 🔥 Bug Description
https://github.com/dotnet/aspire-samples/tree/main/samples/AspireWithJavaScript
i'm clone this repo and generate docker compose in windows 10 
after run dashboard i can't show react angular and vue containers
### 🔍 Steps to Reproduce the Bug
1. clone https://github.com/dotnet/aspire-samples/tree/main/samples/AspireWithJavaScript
2. generate output docker compose
3. run docker compose

### 🧯 Possible Solution
i don't know

**Comment by prom3theu5** [comment]
Hi There

This is due to the fact that we dont generate and inject https dev certs within the built containers.
The nginx configs for each of the js apps all try to use the https port for proxy pass.

All you have to do is do a find and replace on `proxy_pass ${services__weatherapi__https__0};` with `proxy_pass ${services__weatherapi__http__0};`

There should be three file changes - after that it'll run fine :)

**Comment by timeshift92** [comment]
i was changed services__weatherapi__https__0 to  services__weatherapi__http__0, but i wasn't saw react and other frontend services in aspire dashboard

![image](https://github.com/prom3theu5/aspirational-manifests/assets/13614530/656e03cb-54d7-43bf-9aaa-de50baac85cb)
![image](https://github.com/prom3theu5/aspirational-manifests/assets/13614530/1b072f59-a472-423e-985d-49a212f224cb)

**Comment by prom3theu5** [comment]
This is because the aspire manifest doesn't automatically add environmental variables for the containers for those resources unless you do it yourself

You'll have to open a bug on the aspire repo for this

Not to mention the web projects would also need to setup otlp and I dunno if the sample does

**Comment by timeshift92** [comment]
but if you run aspire without docke compose it's worked

**Comment by prom3theu5** [comment]
> but if you run aspire without docke compose it's worked

Aye because that's handled directly by the dcp when aspire runs under debug mode for node apps. Not everything gets output to the manifest though when published, which is the problem. 

They need to ensure that everything is written to the manifest with the extension method they currently use. Aspirate and other third party tools are completely driven by the manifest and if that doesn't contain the info then tools have no way to know

**Comment by timeshift92** [comment]
if I create issue in aspire, can You help me describe this problem?

**Comment by prom3theu5** [comment]
> if I create issue in aspire, can You help me describe this problem?

Yeah sure

The problem is dockerfile resources don't emit environmental variables for OTLP connection to the manifest

You can see here: https://github.com/dotnet/aspire-samples/blob/main/samples/AspireWithJavaScript/AspireJavaScript.AppHost/aspire-manifest.json

The Project (ApiService) has env variables which tools read for OTLP

The docker files do not have these

**Comment by timeshift92** [comment]
oh. I can add this env in react manifest maybe it's helped for see aspire dashboard

**Comment by prom3theu5** [comment]
There are a couple of env vars to add
You need one for service name too

https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/telemetry

**Comment by timeshift92** [comment]
it will be greate if you get me example =( , currently [David Fowler](https://github.com/davidfowl) tell me for not .net family service we need implement aspire otlp service
