### ISSUE TITLE
Reconsider single file/self-contained

### ISSUE THREAD

**Issue by timheuer** [prom3theu5/aspirational-manifests#23]
Right now the project processor is defaulting to `PublishSingleFile=true` and `self-contained` true. These should probably be honored by the project props themselves rather than in this processor.  It would stay consistent with other tools producing container outputs.

**Comment by prom3theu5** [comment]
That makes sense.
With the changes to be made in #24 as well it would mean we are in a better position to read these pre build

**Comment by prom3theu5** [comment]
Covered all props apart from SelfContained in the last lot of work I merged.

Haven't covered SelfContained as eShopLite throws an error when trying to build the CatalogService due to it referencing CatalogDb
"non-self contained executable cannot reference self contained executable"
However both projects do not contain `<SelfContained>true</SelfContained>` in their project files, and 'dotnet msbuild --getProperty:SelfContained' returns false for them both, but you cant publish the container without the CatalogService value being set to true during build.

For now - i've left that defaulting to true.

Going to drop a message in https://github.com/dotnet/aspire/issues/830 about this
eShopLite
